import streamlit as st 
from dotenv import load_dotenv
import os 

from diffusers import StableDiffusionPipeline
import torch

load_dotenv()

def generate_images_using_huggingface_diffusers(text):
    pipe = StableDiffusionPipeline.from_pretrained("runwayml/stable-diffusion-v1-5", torch_dtype=torch.float16)
    pipe = pipe.to("cuda")
    prompt = text
    image = pipe(prompt).images[0] 
    return image

# streamlit app

st.title("AI Image Generation App")
with st.expander("About the App"):
    st.write("This is a simple image generation app that uses AI to generates images from text prompt.")

st.subheader("Image generation using Huggingface Diffusers")
input_prompt = st.text_input("Enter your text prompt")
if input_prompt is not None:
    if st.button("Generate Image"):
        image_output = generate_images_using_huggingface_diffusers(input_prompt)
        st.info("Generating image.....")
        st.success("Image Generated Successfully")
        st.image(image_output, caption="Generated by Huggingface Diffusers")